kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: java:8
  SourceLocation: https://github.com/ja1979/ocpdemo.git
  SourceType: git
  Ports:
  - 8080/TCP
  - 8443/TCP
  - 8778/TCP
  Application: app
  Project: odo
  Name: ocpdemo
  Url:
  - Name: ocpdemo-8080
    Port: 8080
